[build]
    command = "ng build"
    publish = "dist/grammar-rewriter-ai"
    functions = "netlify/functions"

[functions]
    included_files = [".env"]

[dev]
    functions = "netlify/functions" # Tells Netlify where your functions live

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200